apiVersion: v1
kind: Secret
metadata:
  name: agrosmart-secrets
type: Opaque
stringData:
  SECRET_KEY: change-this-in-production
  POSTGRES_PASSWORD: agropass
  DATABASE_URL: postgresql://agro:agropass@agrosmart-postgres:5432/agro_smart
  SMTP_HOST: smtp.example.com
  SMTP_USER: user@example.com
  SMTP_PASSWORD: password
