"""initial schema

Revision ID: b248e9ab10c1
Revises: 
Create Date: 2026-05-18 10:10:59.775084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b248e9ab10c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.drop_index(op.f('ix_data_consents_id'), table_name='data_consents')
    op.drop_table('data_consents')
    op.drop_index(op.f('ix_collaboration_chat_messages_id'), table_name='collaboration_chat_messages')
    op.drop_table('collaboration_chat_messages')
    op.drop_index(op.f('ix_escrow_contracts_id'), table_name='escrow_contracts')
    op.drop_table('escrow_contracts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_legal_audits_id'), table_name='legal_audits')
    op.drop_table('legal_audits')
    op.drop_index(op.f('ix_support_messages_id'), table_name='support_messages')
    op.drop_table('support_messages')
    op.drop_index(op.f('ix_drone_analyses_created_at'), table_name='drone_analyses')
    op.drop_index(op.f('ix_drone_analyses_id'), table_name='drone_analyses')
    op.drop_table('drone_analyses')
    op.drop_index(op.f('ix_annotations_3d_id'), table_name='annotations_3d')
    op.drop_table('annotations_3d')
    op.drop_index(op.f('ix_virtual_appointments_id'), table_name='virtual_appointments')
    op.drop_table('virtual_appointments')
    op.drop_index(op.f('ix_certifications_id'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_webrtc_sessions_id'), table_name='webrtc_sessions')
    op.drop_table('webrtc_sessions')
    op.drop_index(op.f('ix_agricultural_nfts_id'), table_name='agricultural_nfts')
    op.drop_table('agricultural_nfts')
    op.drop_index(op.f('ix_data_usage_logs_id'), table_name='data_usage_logs')
    op.drop_table('data_usage_logs')
    op.drop_index(op.f('ix_smart_contract_transactions_id'), table_name='smart_contract_transactions')
    op.drop_table('smart_contract_transactions')
    op.drop_index(op.f('ix_collaboration_annotations_id'), table_name='collaboration_annotations')
    op.drop_table('collaboration_annotations')
    op.drop_index(op.f('ix_agricultural_certifications_id'), table_name='agricultural_certifications')
    op.drop_table('agricultural_certifications')
    op.drop_index(op.f('ix_collaboration_appointments_id'), table_name='collaboration_appointments')
    op.drop_table('collaboration_appointments')
    op.drop_index(op.f('ix_simulation_scenarios_id'), table_name='simulation_scenarios')
    op.drop_table('simulation_scenarios')
    op.drop_index(op.f('ix_voice_history_id'), table_name='voice_history')
    op.drop_table('voice_history')
    op.add_column('blockchain_traces', sa.Column('product_type', sa.String(), nullable=True))
    op.add_column('blockchain_traces', sa.Column('origin_info', sa.String(), nullable=True))
    op.add_column('blockchain_traces', sa.Column('carbon_score', sa.Float(), nullable=True))
    op.add_column('blockchain_traces', sa.Column('durability_label', sa.String(), nullable=True))
    op.add_column('blockchain_traces', sa.Column('qr_code_data', sa.String(), nullable=True))
    op.add_column('blockchain_traces', sa.Column('verified', sa.Boolean(), nullable=True))
    op.alter_column('blockchain_traces', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('blockchain_traces', 'origin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('blockchain_traces', 'metadata',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_blockchain_traces_created_at'), 'blockchain_traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_blockchain_traces_product_id'), 'blockchain_traces', ['product_id'], unique=False)
    op.drop_constraint(None, 'blockchain_traces', type_='foreignkey')
    op.drop_column('blockchain_traces', 'contract_address')
    op.drop_column('blockchain_traces', 'certification_verified')
    op.drop_column('blockchain_traces', 'crop_id')
    op.drop_column('blockchain_traces', 'blockchain_verified')
    op.add_column('chat_messages', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('chat_messages', sa.Column('session_id', sa.String(), nullable=False))
    op.add_column('chat_messages', sa.Column('content', sa.String(), nullable=False))
    op.add_column('chat_messages', sa.Column('language', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('intent_detected', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('response_generated', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('context_data', sa.String(), nullable=True))
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'users', ['user_id'], ['id'])
    op.drop_column('chat_messages', 'appointment_id')
    op.drop_column('chat_messages', 'sender_id')
    op.drop_column('chat_messages', 'sender_name')
    op.drop_column('chat_messages', 'message')
    op.add_column('community_tokens', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('community_tokens', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('community_tokens', 'balance_after',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('cooperative_contributions', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_cooperative_contributions_created_at'), table_name='cooperative_contributions')
    op.add_column('cooperative_group_purchases', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_cooperative_group_purchases_created_at'), table_name='cooperative_group_purchases')
    op.drop_constraint(None, 'cooperative_members', type_='foreignkey')
    op.add_column('cooperative_purchase_participants', sa.Column('committed_at', sa.DateTime(), nullable=True))
    op.drop_column('cooperative_purchase_participants', 'created_at')
    op.add_column('cooperatives', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('cooperatives', 'region',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cooperatives', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('cooperatives', 'governance_rules',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('cooperatives', 'benefits',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_cooperatives_created_at'), table_name='cooperatives')
    op.drop_index(op.f('ix_cooperatives_region'), table_name='cooperatives')
    op.drop_column('insurances', 'duration_months')
    op.drop_column('loans', 'description')
    op.drop_column('loans', 'duration_months')
    op.drop_column('loans', 'purpose')
    op.alter_column('marketplace_listings', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('marketplace_listings', 'images',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('marketplace_orders', sa.Column('recipient_name', sa.String(), nullable=True))
    op.add_column('marketplace_orders', sa.Column('order_notes', sa.String(), nullable=True))
    op.alter_column('marketplace_orders', 'shipping_address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('marketplace_orders', 'delivered_at')
    op.drop_column('marketplace_orders', 'paid_at')
    op.drop_column('marketplace_orders', 'tracking_number')
    op.drop_column('marketplace_orders', 'payment_tx_hash')
    op.drop_column('marketplace_orders', 'shipped_at')
    op.drop_column('marketplace_orders', 'logistics_provider')
    op.add_column('marketplace_payments', sa.Column('payment_gateway_response', sa.String(), nullable=True))
    op.add_column('marketplace_payments', sa.Column('failure_reason', sa.String(), nullable=True))
    op.add_column('marketplace_payments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('marketplace_payments', 'escrow_release_date')
    op.drop_column('marketplace_payments', 'escrow_released')
    op.alter_column('marketplace_reviews', 'listing_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('marketplace_reviews', 'comment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('marketplace_reviews', 'review_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('marketplace_reviews', 'blockchain_hash')
    op.add_column('sensor_readings', sa.Column('crop_id', sa.Integer(), nullable=True))
    op.add_column('sensor_readings', sa.Column('device_id', sa.String(), nullable=True))
    op.add_column('sensor_readings', sa.Column('metadata', sa.String(), nullable=True))
    op.alter_column('sensor_readings', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_sensor_readings_timestamp'), 'sensor_readings', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'sensor_readings', 'crops', ['crop_id'], ['id'])
    op.drop_column('sensor_readings', 'recorded_at')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.add_column('sensor_readings', sa.Column('recorded_at', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'sensor_readings', type_='foreignkey')
    op.drop_index(op.f('ix_sensor_readings_timestamp'), table_name='sensor_readings')
    op.alter_column('sensor_readings', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('sensor_readings', 'metadata')
    op.drop_column('sensor_readings', 'device_id')
    op.drop_column('sensor_readings', 'crop_id')
    op.add_column('marketplace_reviews', sa.Column('blockchain_hash', sa.VARCHAR(), nullable=True))
    op.alter_column('marketplace_reviews', 'review_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('marketplace_reviews', 'comment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('marketplace_reviews', 'listing_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('marketplace_payments', sa.Column('escrow_released', sa.BOOLEAN(), nullable=True))
    op.add_column('marketplace_payments', sa.Column('escrow_release_date', sa.DATETIME(), nullable=True))
    op.drop_column('marketplace_payments', 'updated_at')
    op.drop_column('marketplace_payments', 'failure_reason')
    op.drop_column('marketplace_payments', 'payment_gateway_response')
    op.add_column('marketplace_orders', sa.Column('logistics_provider', sa.VARCHAR(), nullable=True))
    op.add_column('marketplace_orders', sa.Column('shipped_at', sa.DATETIME(), nullable=True))
    op.add_column('marketplace_orders', sa.Column('payment_tx_hash', sa.VARCHAR(), nullable=True))
    op.add_column('marketplace_orders', sa.Column('tracking_number', sa.VARCHAR(), nullable=True))
    op.add_column('marketplace_orders', sa.Column('paid_at', sa.DATETIME(), nullable=True))
    op.add_column('marketplace_orders', sa.Column('delivered_at', sa.DATETIME(), nullable=True))
    op.alter_column('marketplace_orders', 'shipping_address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('marketplace_orders', 'order_notes')
    op.drop_column('marketplace_orders', 'recipient_name')
    op.alter_column('marketplace_listings', 'images',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('marketplace_listings', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('loans', sa.Column('purpose', sa.VARCHAR(), server_default=sa.text("('')"), nullable=True))
    op.add_column('loans', sa.Column('duration_months', sa.INTEGER(), nullable=True))
    op.add_column('loans', sa.Column('description', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('insurances', sa.Column('duration_months', sa.INTEGER(), nullable=True))
    op.create_index(op.f('ix_cooperatives_region'), 'cooperatives', ['region'], unique=False)
    op.create_index(op.f('ix_cooperatives_created_at'), 'cooperatives', ['created_at'], unique=False)
    op.alter_column('cooperatives', 'benefits',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('cooperatives', 'governance_rules',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('cooperatives', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('cooperatives', 'region',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('cooperatives', 'updated_at')
    op.add_column('cooperative_purchase_participants', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.drop_column('cooperative_purchase_participants', 'committed_at')
    op.create_foreign_key(None, 'cooperative_members', 'users', ['approved_by'], ['id'])
    op.create_index(op.f('ix_cooperative_group_purchases_created_at'), 'cooperative_group_purchases', ['created_at'], unique=False)
    op.drop_column('cooperative_group_purchases', 'updated_at')
    op.create_index(op.f('ix_cooperative_contributions_created_at'), 'cooperative_contributions', ['created_at'], unique=False)
    op.alter_column('cooperative_contributions', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('community_tokens', 'balance_after',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('community_tokens', 'reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('community_tokens', 'updated_at')
    op.add_column('chat_messages', sa.Column('message', sa.TEXT(), nullable=False))
    op.add_column('chat_messages', sa.Column('sender_name', sa.VARCHAR(), nullable=False))
    op.add_column('chat_messages', sa.Column('sender_id', sa.INTEGER(), nullable=True))
    op.add_column('chat_messages', sa.Column('appointment_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'virtual_appointments', ['appointment_id'], ['id'])
    op.create_foreign_key(None, 'chat_messages', 'users', ['sender_id'], ['id'])
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('chat_messages', 'context_data')
    op.drop_column('chat_messages', 'response_generated')
    op.drop_column('chat_messages', 'intent_detected')
    op.drop_column('chat_messages', 'language')
    op.drop_column('chat_messages', 'content')
    op.drop_column('chat_messages', 'session_id')
    op.drop_column('chat_messages', 'user_id')
    op.add_column('blockchain_traces', sa.Column('blockchain_verified', sa.BOOLEAN(), nullable=True))
    op.add_column('blockchain_traces', sa.Column('crop_id', sa.INTEGER(), nullable=False))
    op.add_column('blockchain_traces', sa.Column('certification_verified', sa.BOOLEAN(), nullable=True))
    op.add_column('blockchain_traces', sa.Column('contract_address', sa.VARCHAR(), nullable=True))
    op.create_foreign_key(None, 'blockchain_traces', 'crops', ['crop_id'], ['id'])
    op.drop_index(op.f('ix_blockchain_traces_product_id'), table_name='blockchain_traces')
    op.drop_index(op.f('ix_blockchain_traces_created_at'), table_name='blockchain_traces')
    op.alter_column('blockchain_traces', 'metadata',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('blockchain_traces', 'origin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blockchain_traces', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('blockchain_traces', 'verified')
    op.drop_column('blockchain_traces', 'qr_code_data')
    op.drop_column('blockchain_traces', 'durability_label')
    op.drop_column('blockchain_traces', 'carbon_score')
    op.drop_column('blockchain_traces', 'origin_info')
    op.drop_column('blockchain_traces', 'product_type')
    op.create_table('voice_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('language', sa.VARCHAR(), nullable=False),
    sa.Column('recognized_text', sa.TEXT(), nullable=False),
    sa.Column('response_text', sa.TEXT(), nullable=True),
    sa.Column('intent', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_history_id'), 'voice_history', ['id'], unique=False)
    op.create_table('simulation_scenarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('crop', sa.VARCHAR(), nullable=False),
    sa.Column('region', sa.VARCHAR(), nullable=False),
    sa.Column('soil_type', sa.VARCHAR(), nullable=False),
    sa.Column('baseline_rainfall', sa.FLOAT(), nullable=False),
    sa.Column('baseline_fertilizer', sa.FLOAT(), nullable=False),
    sa.Column('baseline_temperature', sa.FLOAT(), nullable=True),
    sa.Column('irrigation_change_pct', sa.FLOAT(), nullable=True),
    sa.Column('fertilizer_change_pct', sa.FLOAT(), nullable=True),
    sa.Column('result_data', sa.TEXT(), nullable=False),
    sa.Column('share_token', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index(op.f('ix_simulation_scenarios_id'), 'simulation_scenarios', ['id'], unique=False)
    op.create_table('collaboration_appointments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('expert_name', sa.VARCHAR(), nullable=False),
    sa.Column('scheduled_at', sa.DATETIME(), nullable=False),
    sa.Column('topic', sa.VARCHAR(), nullable=False),
    sa.Column('farm_location', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('session_recording_url', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaboration_appointments_id'), 'collaboration_appointments', ['id'], unique=False)
    op.create_table('agricultural_certifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('certification_type', sa.VARCHAR(), nullable=False),
    sa.Column('certification_body', sa.VARCHAR(), nullable=False),
    sa.Column('certificate_number', sa.VARCHAR(), nullable=False),
    sa.Column('issued_date', sa.DATETIME(), nullable=False),
    sa.Column('expiry_date', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('requirements_met', sa.TEXT(), nullable=True),
    sa.Column('audit_report', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_number')
    )
    op.create_index(op.f('ix_agricultural_certifications_id'), 'agricultural_certifications', ['id'], unique=False)
    op.create_table('collaboration_annotations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('annotation_type', sa.VARCHAR(), nullable=False),
    sa.Column('x_position', sa.FLOAT(), nullable=False),
    sa.Column('y_position', sa.FLOAT(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['collaboration_appointments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaboration_annotations_id'), 'collaboration_annotations', ['id'], unique=False)
    op.create_table('smart_contract_transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trace_id', sa.INTEGER(), nullable=False),
    sa.Column('tx_hash', sa.VARCHAR(), nullable=False),
    sa.Column('function_name', sa.VARCHAR(), nullable=False),
    sa.Column('input_data', sa.TEXT(), nullable=True),
    sa.Column('output_data', sa.TEXT(), nullable=True),
    sa.Column('gas_used', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('blockchain_timestamp', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('confirmed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['blockchain_traces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_index(op.f('ix_smart_contract_transactions_id'), 'smart_contract_transactions', ['id'], unique=False)
    op.create_table('data_usage_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('data_category', sa.VARCHAR(), nullable=False),
    sa.Column('purpose', sa.VARCHAR(), nullable=False),
    sa.Column('performed_by', sa.VARCHAR(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('consent_verified', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_usage_logs_id'), 'data_usage_logs', ['id'], unique=False)
    op.create_table('agricultural_nfts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trace_id', sa.INTEGER(), nullable=False),
    sa.Column('token_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('attributes', sa.TEXT(), nullable=False),
    sa.Column('supply_chain_stage', sa.VARCHAR(), nullable=False),
    sa.Column('contract_address', sa.VARCHAR(), nullable=True),
    sa.Column('owner_address', sa.VARCHAR(), nullable=True),
    sa.Column('minted_at', sa.DATETIME(), nullable=True),
    sa.Column('transferred_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['blockchain_traces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id')
    )
    op.create_index(op.f('ix_agricultural_nfts_id'), 'agricultural_nfts', ['id'], unique=False)
    op.create_table('webrtc_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), nullable=False),
    sa.Column('initiator_id', sa.INTEGER(), nullable=True),
    sa.Column('session_type', sa.VARCHAR(), nullable=True),
    sa.Column('participant_ids', sa.VARCHAR(), nullable=True),
    sa.Column('session_metadata', sa.TEXT(), nullable=True),
    sa.Column('session_id', sa.VARCHAR(), nullable=False),
    sa.Column('offer_sdp', sa.TEXT(), nullable=True),
    sa.Column('answer_sdp', sa.TEXT(), nullable=True),
    sa.Column('ice_candidates', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('ended_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['virtual_appointments.id'], ),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_webrtc_sessions_id'), 'webrtc_sessions', ['id'], unique=False)
    op.create_table('certifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trace_id', sa.INTEGER(), nullable=False),
    sa.Column('cert_type', sa.VARCHAR(), nullable=False),
    sa.Column('issuer', sa.VARCHAR(), nullable=False),
    sa.Column('verified', sa.BOOLEAN(), nullable=True),
    sa.Column('verification_date', sa.DATETIME(), nullable=True),
    sa.Column('expiry_date', sa.DATETIME(), nullable=True),
    sa.Column('metadata', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['blockchain_traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certifications_id'), 'certifications', ['id'], unique=False)
    op.create_table('virtual_appointments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('expert_name', sa.VARCHAR(), nullable=False),
    sa.Column('expert_specialty', sa.VARCHAR(), nullable=True),
    sa.Column('scheduled_at', sa.DATETIME(), nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), nullable=True),
    sa.Column('topic', sa.VARCHAR(), nullable=False),
    sa.Column('farm_location', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('meeting_link', sa.VARCHAR(), nullable=True),
    sa.Column('recording_url', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('cancelled_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_appointments_id'), 'virtual_appointments', ['id'], unique=False)
    op.create_table('annotations_3d',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('annotation_type', sa.VARCHAR(), nullable=False),
    sa.Column('position_x', sa.FLOAT(), nullable=False),
    sa.Column('position_y', sa.FLOAT(), nullable=False),
    sa.Column('position_z', sa.FLOAT(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['virtual_appointments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_3d_id'), 'annotations_3d', ['id'], unique=False)
    op.create_table('drone_analyses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=True),
    sa.Column('result_json', sa.TEXT(), nullable=False),
    sa.Column('severity', sa.VARCHAR(), nullable=False),
    sa.Column('disease_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drone_analyses_id'), 'drone_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_drone_analyses_created_at'), 'drone_analyses', ['created_at'], unique=False)
    op.create_table('support_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('response', sa.TEXT(), nullable=True),
    sa.Column('responded_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_messages_id'), 'support_messages', ['id'], unique=False)
    op.create_table('legal_audits',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('audit_id', sa.VARCHAR(), nullable=False),
    sa.Column('audit_type', sa.VARCHAR(), nullable=False),
    sa.Column('scope', sa.TEXT(), nullable=False),
    sa.Column('results', sa.TEXT(), nullable=False),
    sa.Column('compliance_score', sa.FLOAT(), nullable=False),
    sa.Column('performed_by', sa.VARCHAR(), nullable=False),
    sa.Column('performed_at', sa.DATETIME(), nullable=True),
    sa.Column('next_audit_due', sa.DATETIME(), nullable=True),
    sa.Column('recommendations', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('third_party_validator', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id')
    )
    op.create_index(op.f('ix_legal_audits_id'), 'legal_audits', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('alert_type', sa.VARCHAR(), nullable=False),
    sa.Column('severity', sa.VARCHAR(), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('escrow_contracts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('buyer_address', sa.VARCHAR(), nullable=False),
    sa.Column('seller_address', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('escrow_address', sa.VARCHAR(), nullable=True),
    sa.Column('contract_address', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('release_conditions', sa.TEXT(), nullable=False),
    sa.Column('funded_at', sa.DATETIME(), nullable=True),
    sa.Column('released_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['marketplace_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escrow_contracts_id'), 'escrow_contracts', ['id'], unique=False)
    op.create_table('collaboration_chat_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('is_expert', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['collaboration_appointments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaboration_chat_messages_id'), 'collaboration_chat_messages', ['id'], unique=False)
    op.create_table('data_consents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('consent_type', sa.VARCHAR(), nullable=False),
    sa.Column('consent_given', sa.BOOLEAN(), nullable=True),
    sa.Column('consent_date', sa.DATETIME(), nullable=True),
    sa.Column('consent_expiry', sa.DATETIME(), nullable=True),
    sa.Column('purpose', sa.TEXT(), nullable=False),
    sa.Column('data_categories', sa.TEXT(), nullable=True),
    sa.Column('third_parties', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('withdrawal_date', sa.DATETIME(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_consents_id'), 'data_consents', ['id'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
